#!/bin/bash

jupyter contrib nbextension install --user

echo "downloading image files..."
wget -O all-events.zip "https://raw.githubusercontent.com/ntiltmann/opal-mc-ml/main/all-events.zip"
echo "unzipping..."
unzip all-events.zip
echo "done!"
